global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'echo-app'
    static_configs:
      - targets: ['app:8080']
        labels:
          service: 'echo-application'
